/*
 * generated by Xtext 2.33.0
 */
/*
 * Copyright (c) 2022 - 2024 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.ui.outline;

//import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

import com.epistimis.uddl.ui.outline.UddlOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class FaceOutlineTreeProvider extends UddlOutlineTreeProvider { // DefaultOutlineTreeProvider {

}
