/*
 * generated by Xtext 2.33.0
 */
/*
 * Copyright (c) 2022 - 2024 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.ide;


/**
 * Use this class to register ide components.
 */
public class FaceIdeModule extends AbstractFaceIdeModule {
}
